### ISSUE TITLE
Fail to create scatter_example.engine

### ISSUE THREAD

**Issue by dl19940602** [wy17646051/tensorrt_scatter#1]
Hello.thank you for your publish, I follow your instrument and build libtensorrtscatter.so successfully, but when i try to convert scatter_example.onnx to engine file ,it occur erros as follow

`[06/28/2023-09:11:03] [TRT] [E] ModelImporter.cpp:773: While parsing node number 4 [TRTS_Scatter -> "out"]:
[06/28/2023-09:11:03] [TRT] [E] ModelImporter.cpp:774: --- Begin node ---
[06/28/2023-09:11:03] [TRT] [E] ModelImporter.cpp:775: input: "src"
input: "tensorrt_scatter::TRTS_Scatter_6"
input: "base"
output: "out"
output: "arg_out"
name: "TRTS_Scatter_4"
op_type: "TRTS_Scatter"
attribute {
  name: "dim"
  i: 1
  type: INT
}
attribute {
  name: "dim_size"
  i: 10000
  type: INT
}
attribute {
  name: "reduce"
  s: "max"
  type: STRING
}
domain: "tensorrt_scatter"

[06/28/2023-09:11:03] [TRT] [E] ModelImporter.cpp:776: --- End node ---
[06/28/2023-09:11:03] [TRT] [E] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4898 In function importFallbackPluginImporter:
[8] Assertion failed: plugin && "Could not create plugin"`

I print the registried plugin,it shows that 'TRTS_Scatter' is registered aleardy, but still fail to create engine, looking forward to yourfeedback, thank you!

**Comment by wy17646051** [comment]
May I ask what version of TensorRT and CUDA you are using

**Comment by dl19940602** [comment]
> May I ask what version of TensorRT and CUDA you are using
Hello, version of TensorRT and CUDA is:
TensorRT version 8.5.1.7
CUDA version 11.6
Pytorch version 2.0.0+cu118
Python version 3.10
 

ldd libtensorrtscatter.so
        linux-vdso.so.1 =>  (0x00007ffdf6355000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc4bc5e1000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc4bc3d9000)
        libnvinfer.so.8 => /home/jovyan/cfs/personal_data/donglin/TensorRT-8.5.1.7/lib/libnvinfer.so.8 (0x00007fc49eba2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc49e985000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc49e603000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc49e3ed000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc49e023000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc4bcced000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc49dd1a000)

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

I test your repo in A100 machine,I have try tensorrt-8.5.1,tensorrt=8.5.3,tensorrt-8.6.1,but it still comes with the above errors,

**Comment by wy17646051** [comment]
Sorry to notice your further comment so late, based on your issue we initialized a new VM with 3090 and re-tested it as set up in the README.md. Our tests did not show the problem.

We suspected that your TensorRT for Python is correctly installed. If you install manually from the files in the TensorRT TAR, it may overlook some details, resulting in difficult to solve errors. We recommend you by the `pip install tensorrt` command to re-install and try again.  

Or try to modify the `CUDA_ARCHITECTURES` parameter in the 9 line of the `CMakeLists.txt` file (eg. 86) and try again

If this still doesn't solve your problem, still hope you can ask us further.

**Comment by dl19940602** [comment]
> Sorry to notice your further comment so late, based on your issue we initialized a new VM with 3090 and re-tested it as set up in the README.md. Our tests did not show the problem.
> 
> We suspected that your TensorRT for Python is correctly installed. If you install manually from the files in the TensorRT TAR, it may overlook some details, resulting in difficult to solve errors. We recommend you by the `pip install tensorrt` command to re-install and try again.
> 
> Or try to modify the `CUDA_ARCHITECTURES` parameter in the 9 line of the `CMakeLists.txt` file (eg. 86) and try again
> 
> If this still doesn't solve your problem, still hope you can ask us further.

Thank you for your reply! I re-install the tensorrt follow our recommend(pip install tensorrt==8.5.3.1) and re-build the cmake project, It successfully register plugin and generate engine file, I will keep focus on your git repo, and now you could close the issue, thank you for your guidance again!

**Comment by Siyeong-Lee** [comment]
@dl19940602 I followed the author's instructions, but it is not building properly.  However, based on the above issue, it appears that you have successfully built it. Could you share your environment and know-how?

* https://github.com/wy17646051/tensorrt_scatter/issues/3#issue-1857650716
